version: 2
jobs:
    build:
        working_directory: ~/ngx-validator
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - restore_cache:
                  key: ngx-validator-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - run: npm install
            - save_cache:
                  key: ngx-validator-{{ .Branch }}-{{ checksum "package-lock.json" }}
                  paths:
                      - 'node_modules'
            - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
            - run: npm run report-coverage
